### ISSUE TITLE
Coin Logo

### ISSUE THREAD

**Issue by Traxo7** [jvanname/circcash#2]
Do not criticize the logo unless you have stake in the currency.

**Comment by jvanname** [comment]
The logo arises from a mathematical object called a Laver table. The Laver tables arise from extremely large infinities known as rank-into-rank cardinals and n-huge cardinals.

https://arxiv.org/pdf/1812.02761.pdf

(see also Chapter 11 in the Handbook of Set Theory and Chapters 10-13 in the book Braids and Self-Distributivity)

From the Laver tables, one obtains a rather complicated looking fractal, so the image in question is just a portion of that fractal that looks reasonably tame.

I do not have any alternative logo in mind, and I currently do not have any plan to offer a bounty for changing the logo. There are other images however that need an update, and I do plan on offering a bounty for updating those images.

**Comment by TraderChinese** [comment]
Is the coin ready to be mined?

**Comment by jvanname** [comment]
Circcash has been publicly available for mining for over a month.

**Comment by jvanname** [comment]
I do not need anyone who is unwilling to sponsor Circcash to criticize the Logo.

**Comment by Traxo7** [comment]
I am eagerly waiting for a sponsor who will compliment the Logo. Hope they can let me know once they do so.

**Comment by jvanname** [comment]
I do not take advice from people who are unwilling to sponsor.
