### ISSUE TITLE
Where is the compiled WINDOWS version?

### ISSUE THREAD

**Issue by TraderChinese** [jvanname/circcash#3]
How do you mine?

**Comment by TraderChinese** [comment]
Another unfair coin.

**Comment by jvanname** [comment]
You are clearly not interested in Circcash. Please learn about reversible computation so that you understand the science behind Circcash. I will only help you if you have a legitimate interest in using Circcash. Your opinion about Circcash only has value if you have stake in Circcash.

**Comment by jvanname** [comment]
Right now, Circcash is only available for Linux Ubuntu (I could get it to work for versions 16 and 18 but not on Version 20). It is quite straightforward to install Ubuntu on your hard drive using a live USB or to use a Ubuntu virtual machine (you can use Virtualbox to run your virtual machines).  I will make a Windows executable for Circcash in the near future. Circcash was just launched, so I have not had a chance to do this yet.

**Comment by jvanname** [comment]
I have created Windows executables that people can use to mine Circcash, but at the moment, I will not release the Windows executable to the public since I currently do not have anyone sponsoring my work here on Github.
