### ISSUE TITLE
No Wallet File Anymore only Source

### ISSUE THREAD

**Issue by SickProdigy** [jvanname/circcash#9]
Why pull the software and only leave the source?

**Comment by QuickMythril** [comment]
The installer is already part of the repository.  You can find it here:

https://github.com/jvanname/circcash/raw/master/circcash-0.8.7.5-win32-setup.exe

Edit:  It is also linked in the Readme file and the Downloads page on the Circcash website:
https://github.com/jvanname/circcash/blob/master/README.md
https://circcashcore.com/downloads-2/
